const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "Name", uid: "name", sortable: true },
    { name: "Age", uid: "age", sortable: true },
    { name: "Role", uid: "role", sortable: true },
    { name: "Team", uid: "team" },
    { name: "Email", uid: "email" },
    { name: "Status", uid: "status", sortable: true },
    { name: "Actions", uid: "actions" },
    { name: "Id Marca", uid: "id_marca", sortable: true },
    { name: "Center Origen Lat", uid: "center_origen_lat" },
    { name: "Center Origen Lon", uid: "center_origen_lon" },
    { name: "Center Destino Lat", uid: "center_destino_lat" },
    { name: "Center Destino Lon", uid: "center_destino_lon" },
        { name: "Nombre Origen Ubicacion", uid: "nombre_origen_ubicacion" },
    { name: "Nombre Destino Ubicacion", uid: "nombre_destino_ubicacion" },
    
    { name: "Tiempo Demora Establecido", uid: "tiempo_demora_establecido" },
    { name: "Hora Inicio Establecido", uid: "hora_inicio_establecido" },
    { name: "Hora Inicio Establecido Str", uid: "hora_inicio_establecido_str" },
    { name: "Hora Termino Establecido", uid: "hora_termino_establecido" },
    { name: "Hora Termino Establecido Str", uid: "hora_termino_establecido_str" },
    { name: "Is End", uid: "isEnd" },
    { name: "Is Lap Finish", uid: "isLapFinish" },
    { name: "Laps", uid: "laps" },
    { name: "Id Trip", uid: "id_trip" },
    { name: "Diferencia Tiempo", uid: "diferencia_tiempo" },
    { name: "Hora Marca", uid: "hora_marca" },
    { name: "Hora Marca Formated", uid: "hora_marca_formated" },
    { name: "State", uid: "state", sortable: true }
];


const statusOptions = [
    { name: "Temprano", uid: "temprano" },
    { name: "Tarde", uid: "tarde" },
    { name: "Ultimo minuto", uid: "ultimo_minuto" },
];

const users = [
    {
        id: 1,
        name: "Tony Reichert",
        role: "CEO",
        team: "Management",
        status: "active",
        age: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        email: "tony.reichert@example.com",
             "id_marca": 1,
                    "center_origen_lat": -12.0464,
                    "center_origen_lon": -77.0428,
                    "center_destino_lat": -12.0456,
                    "center_destino_lon": -77.0412,
                    "nombre_destino_ubicacion": "Destino XYZ",
                    "nombre_origen_ubicacion": "Origen ABC",
                    "tiempo_demora_establecido": "10 minutes",
                    "hora_inicio_establecido": "2024-08-06T08:00:00",
                    "hora_inicio_establecido_str": "08:00",
                    "hora_termino_establecido": "2024-08-06T09:00:00",
                    "hora_termino_establecido_str": "09:00",
                    "isEnd": 0,
                    "isLapFinish": 0,
                    "laps": 3,
                    "id_trip": 9,
                    "diferencia_tiempo": "00:05:00",
                    "hora_marca": "2024-08-06T09:18:24.2830000000",
                    "hora_marca_formated": "2024-08-06T09:18:24.283Z",
                    "state": "PENDING"
    },
    {
        id: 2,
        name: "Zoey Lang",
        role: "Tech Lead",
        team: "Development",
        status: "paused",
        age: "25",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        email: "zoey.lang@example.com",
             "id_marca": 2,
                    "center_origen_lat": -12.0464,
                    "center_origen_lon": -77.0428,
                    "center_destino_lat": -12.0456,
                    "center_destino_lon": -77.0412,
                    "nombre_destino_ubicacion": "Destino XYZ",
                    "nombre_origen_ubicacion": "Origen ABC",
                    "tiempo_demora_establecido": "10 minutes",
                    "hora_inicio_establecido": "2024-08-06T08:00:00",
                    "hora_inicio_establecido_str": "08:00",
                    "hora_termino_establecido": "2024-08-06T09:00:00",
                    "hora_termino_establecido_str": "09:00",
                    "isEnd": 0,
                    "isLapFinish": 0,
                    "laps": 3,
                    "id_trip": 9,
                    "diferencia_tiempo": "00:05:00",
                    "hora_marca": "2024-08-06T09:18:24.2830000000",
                    "hora_marca_formated": "2024-08-06T09:18:24.283Z",
                    "state": "PENDING"
    },
    {
        id: 3,
        name: "Jane Fisher",
        role: "Sr. Dev",
        team: "Development",
        status: "active",
        age: "22",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        email: "jane.fisher@example.com",
             "id_marca": 3,
                    "center_origen_lat": -12.0464,
                    "center_origen_lon": -77.0428,
                    "center_destino_lat": -12.0456,
                    "center_destino_lon": -77.0412,
                    "nombre_destino_ubicacion": "Destino XYZ",
                    "nombre_origen_ubicacion": "Origen ABC",
                    "tiempo_demora_establecido": "10 minutes",
                    "hora_inicio_establecido": "2024-08-06T08:00:00",
                    "hora_inicio_establecido_str": "08:00",
                    "hora_termino_establecido": "2024-08-06T09:00:00",
                    "hora_termino_establecido_str": "09:00",
                    "isEnd": 0,
                    "isLapFinish": 0,
                    "laps": 3,
                    "id_trip": 9,
                    "diferencia_tiempo": "00:05:00",
                    "hora_marca": "2024-08-06T09:18:24.2830000000",
                    "hora_marca_formated": "2024-08-06T09:18:24.283Z",
                    "state": "PENDING"
    },
  
];

export { columns, statusOptions, users };

